(("default" . ((user-emacs-directory . "~/.emacs.default") (server-name . "default")))
("doom" . ((user-emacs-directory . "~/Code/doom-emacs") (server-name . "doom")))
("syscraft" . ((user-emacs-directory . "~/.emacs.syscraft") (server-name . "syscraft")))
("personal" . ((user-emacs-directory . "~/.emacs.personal") (server-name . "personal")))
("crafted-emacs". ((user-emacs-directory . "~/.emacs.crafted") (server-name . "crafted"))))
